services:
  decypharr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: local
        CHANNEL: dev
    image: decypharr:local
    container_name: decypharr
    ports:
      - "8282:8282"
    volumes:
      - /mnt/:/mnt:rshared
      - ./configs/:/app
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
